services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - .env
  db:
    restart: always
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      - POSTGRES_PASSWORD=node_service_password
      - POSTGRES_USER=node_service_user
      - POSTGRES_DB=node_service
    ports:
      - "5432:5432"
