services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      - POSTGRES_PASSWORD=node_service_password
      - POSTGRES_USER=node_service_user
      - POSTGRES_DB=node_service
    ports:
      - "5432:5432"
